"""Backward-compatible facade for :mod:`promptcontrollab.integrations.hf_demo`."""

from promptcontrollab.integrations.hf_demo import (
    HF_DEMO_ALLOWED_WORKFLOWS,
    HF_DEMO_MAX_GLOBAL_BYTES,
    HF_DEMO_MAX_JSON_DEPTH,
    HF_DEMO_MAX_JSON_NODES,
    HF_DEMO_MAX_JSON_RECORDS,
    HF_DEMO_MAX_SESSION_BYTES,
    HF_DEMO_MAX_SESSION_FILES,
    HF_DEMO_MAX_SESSIONS,
    HF_DEMO_MAX_UPLOAD_BYTES,
    HF_DEMO_MODE,
    HF_DEMO_SESSION_TTL_SECONDS,
    DemoSession,
    cleanup_expired_sessions,
    is_hf_demo,
    prepare_demo_session,
    require_hf_demo_workflow,
    store_uploaded_artifact,
    validate_uploaded_artifact,
)

__all__ = [
    "HF_DEMO_ALLOWED_WORKFLOWS",
    "HF_DEMO_MAX_GLOBAL_BYTES",
    "HF_DEMO_MAX_JSON_DEPTH",
    "HF_DEMO_MAX_JSON_NODES",
    "HF_DEMO_MAX_JSON_RECORDS",
    "HF_DEMO_MAX_SESSION_BYTES",
    "HF_DEMO_MAX_SESSION_FILES",
    "HF_DEMO_MAX_SESSIONS",
    "HF_DEMO_MAX_UPLOAD_BYTES",
    "HF_DEMO_MODE",
    "HF_DEMO_SESSION_TTL_SECONDS",
    "DemoSession",
    "cleanup_expired_sessions",
    "is_hf_demo",
    "prepare_demo_session",
    "require_hf_demo_workflow",
    "store_uploaded_artifact",
    "validate_uploaded_artifact",
]
