"""Backward-compatible facade for :mod:`promptcontrollab.integrations.templates`."""

from promptcontrollab.integrations.templates import (
    BASELINE_JSONL,
    CANDIDATE_JSONL,
    CONFIG_YAML,
    DEEPEVAL_BASELINE_JSON,
    DEEPEVAL_CANDIDATE_JSON,
    EXTERNAL_README_MD,
    GATE_POLICY_YAML,
    GUARD_POLICY_YAML,
    LANGFUSE_EXPORT_JSON,
    LANGSMITH_RUNS_CSV,
    PROJECT_CONFIG_YAML,
    PROJECT_README_MD,
    PROJECT_README_ZH_MD,
    PROMPT_OPTIMIZER_FAVORITES_JSON,
    PROMPTFOO_RESULTS_JSON,
    TASKS_JSONL,
    write_example_project,
    write_external_examples,
)

__all__ = [
    "BASELINE_JSONL",
    "CANDIDATE_JSONL",
    "CONFIG_YAML",
    "DEEPEVAL_BASELINE_JSON",
    "DEEPEVAL_CANDIDATE_JSON",
    "EXTERNAL_README_MD",
    "GATE_POLICY_YAML",
    "GUARD_POLICY_YAML",
    "LANGFUSE_EXPORT_JSON",
    "LANGSMITH_RUNS_CSV",
    "PROJECT_CONFIG_YAML",
    "PROJECT_README_MD",
    "PROJECT_README_ZH_MD",
    "PROMPT_OPTIMIZER_FAVORITES_JSON",
    "PROMPTFOO_RESULTS_JSON",
    "TASKS_JSONL",
    "write_example_project",
    "write_external_examples",
]
