"""Example project templates for ``pcl init``."""

from __future__ import annotations

from pathlib import Path

from promptcontrollab.files import ensure_dir

TASKS_JSONL = """\
{"id":"arith-1","input":"What is 2 + 2?","expected":"4","slice":"arithmetic"}
{"id":"arith-2","input":"What is 10 - 3?","expected":"7","slice":"arithmetic"}
{"id":"format-1","input":"Return the label POSITIVE.","expected":"POSITIVE","slice":"format"}
{"id":"format-2","input":"Return the label NEGATIVE.","expected":"NEGATIVE","slice":"format"}
"""

BASELINE_JSONL = """\
{"id":"arith-1","output":"4","provider":"openai","model":"gpt-4o"}
{"id":"arith-2","output":"6","provider":"openai","model":"gpt-4o"}
{"id":"format-1","output":"POSITIVE","provider":"openai","model":"gpt-4o"}
{"id":"format-2","output":"negative","provider":"openai","model":"gpt-4o"}
"""

CANDIDATE_JSONL = """\
{"id":"arith-1","output":"4","provider":"openai","model":"gpt-4o"}
{"id":"arith-2","output":"7","provider":"openai","model":"gpt-4o"}
{"id":"format-1","output":"POSITIVE","provider":"openai","model":"gpt-4o"}
{"id":"format-2","output":"NEGATIVE","provider":"openai","model":"gpt-4o"}
"""

CONFIG_YAML = """\
# PromptControlLab Quick Mode example.
mode: quick
data: examples/tasks.jsonl
metric: exact_match
baseline_predictions: examples/predictions_baseline.jsonl
candidate_predictions: examples/predictions_candidate.jsonl
prompt_file: prompts/current.txt
prompt_id: demo-prompt
prompt_version: v1
baseline_model: gpt-4o
candidate_model: gpt-4o
baseline_provider: openai
candidate_provider: openai
out: runs/quick
explain_level: plain
gate_policy: examples/gate.policy.yaml
"""

GUARD_POLICY_YAML = """\
# Example guard policy for `pcl guard --policy`.
# The parser is dependency-free. It supports this flat style and a small nested `rules:` style.
profile: coding
block_at: high
review_at: medium
required_fields: target_files,failing_behavior,test_plan,acceptance_criteria
rule.destructive_action.severity: high
rule.destructive_action.patterns: delete database|drop table|remove auth
rule.destructive_action.message: Coding prompt asks for a destructive change.
rule.destructive_action.category: destructive_change
rule.broad_refactor.severity: medium
rule.broad_refactor.patterns: refactor whole repo|rewrite all
rule.broad_refactor.message: Broad refactors need human review before an agent runs.
rule.broad_refactor.category: broad_refactor
"""

GATE_POLICY_YAML = """\
# Example gate policy for `pcl gate`.
min_candidate_score: 0.75
max_regression: 0.0
require_adjusted_p_below: 1.0
allowed_models: gpt-4o,gpt-5.2
allowed_providers: openai
block_if_model_unknown: true
block_if_model_mismatch: true
block_if_alias_model: false
require_model_verified: false
"""

PROJECT_CONFIG_YAML = """\
# Project defaults for local PromptControlLab commands.
guard_policy: examples/guard.policy.yaml
gate_policy: examples/gate.policy.yaml
runs_dir: runs
expected_paths:
  - src
  - tests
test_commands:
  - pytest
allowed_models: gpt-4o,gpt-5.2
ui.default_view: workflows
"""

PROJECT_README_MD = """\
# PromptControlLab Example Project

This folder was generated by `pcl init`. It contains a tiny prompt-evaluation
fixture, example guard/gate policies, and project defaults in `.promptcontrol.yaml`.
Chinese guide: [README.zh.md](README.zh.md).

## First step

If you want a fresh project and report in one command, run this from outside
this folder:

```bash
pcl quickstart --out demo
# same as: pcl start --choice demo --out demo
```

If you are already inside this folder and want help choosing another workflow, run:

```bash
pcl start --guide
```

## Copy-paste paths

```bash
# Refresh the quick report from the bundled predictions
pcl analyze --config promptcontrol.example.yaml --out runs/quick

# Gate the quick report with the example policy
pcl gate --run runs/quick --policy examples/gate.policy.yaml

# Open the local dashboard
pcl ui --runs runs --policy examples/guard.policy.yaml
```

## What the files mean

- `examples/tasks.jsonl`: tiny task set.
- `examples/predictions_baseline.jsonl`: baseline prompt outputs.
- `examples/predictions_candidate.jsonl`: candidate prompt outputs.
- `examples/guard.policy.yaml`: prompt preflight policy for `pcl guard`.
- `examples/gate.policy.yaml`: report/model gate policy for `pcl gate`.
- `promptcontrol.example.yaml`: quick analysis config.
- `.promptcontrol.yaml`: project defaults for local commands.

The example is intentionally small. Use it to learn the artifact shape, then
replace the data and predictions with your own evaluation results.
"""

PROJECT_README_ZH_MD = """\
# PromptControlLab 示例项目

这个目录由 `pcl init` 生成, 里面包含一个很小的 prompt 评测样例、guard/gate
策略文件, 以及 `.promptcontrol.yaml` 项目默认配置。英文说明见 [README.md](README.md)。

## 第一步

如果你想一条命令创建新项目并直接生成报告, 在当前目录外运行:

```bash
pcl quickstart --language zh --out demo
# 同: pcl start --choice demo --language zh --out demo
```

如果你已经在这个目录里, 想继续选择其他流程, 运行:

```bash
pcl start --guide --language zh
```

## 可复制命令

```bash
# 使用内置预测结果刷新 quick report
pcl analyze --config promptcontrol.example.yaml --out runs/quick

# 用示例策略检查 quick report
pcl gate --run runs/quick --policy examples/gate.policy.yaml

# 打开本地仪表盘
pcl ui --runs runs --policy examples/guard.policy.yaml
```

## 文件说明

- `examples/tasks.jsonl`: 很小的任务集。
- `examples/predictions_baseline.jsonl`: baseline prompt 的输出。
- `examples/predictions_candidate.jsonl`: candidate prompt 的输出。
- `examples/guard.policy.yaml`: 给 `pcl guard` 用的执行前检查策略。
- `examples/gate.policy.yaml`: 给 `pcl gate` 用的报告/模型门禁策略。
- `promptcontrol.example.yaml`: quick analysis 配置。
- `.promptcontrol.yaml`: 本项目的本地命令默认值。

这个示例故意很小。先用它理解 artifact 长什么样, 然后把数据和预测结果替换成你自己的评测结果。
"""

PROMPTFOO_RESULTS_JSON = """\
{
  "version": 3,
  "timestamp": "2026-06-13T00:00:00Z",
  "prompts": [
    {
      "id": "baseline",
      "raw": "Answer the question.",
      "label": "Baseline"
    },
    {
      "id": "candidate",
      "raw": "Answer with only the final result. Follow the requested output format exactly.",
      "label": "Candidate"
    }
  ],
  "results": [
    {
      "promptId": "baseline",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 0,
      "testCase": {"vars": {"slice": "arithmetic"}, "assert": [{"type": "equals", "value": "4"}]},
      "response": {"output": "wrong"},
      "success": false,
      "score": 0
    },
    {
      "promptId": "candidate",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 0,
      "testCase": {"vars": {"slice": "arithmetic"}, "assert": [{"type": "equals", "value": "4"}]},
      "response": {"output": "4"},
      "success": true,
      "score": 1
    },
    {
      "promptId": "baseline",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 1,
      "testCase": {"vars": {"slice": "format"}, "assert": [{"type": "equals", "value": "YES"}]},
      "response": {"output": "NO"},
      "success": false,
      "score": 0
    },
    {
      "promptId": "candidate",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 1,
      "testCase": {"vars": {"slice": "format"}, "assert": [{"type": "equals", "value": "YES"}]},
      "response": {"output": "YES"},
      "success": true,
      "score": 1
    },
    {
      "promptId": "baseline",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 2,
      "testCase": {
        "vars": {"slice": "classification"},
        "assert": [{"type": "equals", "value": "blue"}]
      },
      "response": {"output": "blue"},
      "success": true,
      "score": 1
    },
    {
      "promptId": "candidate",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 2,
      "testCase": {
        "vars": {"slice": "classification"},
        "assert": [{"type": "equals", "value": "blue"}]
      },
      "response": {"output": "blue"},
      "success": true,
      "score": 1
    },
    {
      "promptId": "baseline",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 3,
      "testCase": {"vars": {"slice": "safety"}, "assert": [{"type": "equals", "value": "safe"}]},
      "response": {"output": "maybe"},
      "success": false,
      "score": 0
    },
    {
      "promptId": "candidate",
      "provider": {"id": "openai:gpt-4o-mini-20260601"},
      "testIdx": 3,
      "testCase": {"vars": {"slice": "safety"}, "assert": [{"type": "equals", "value": "safe"}]},
      "response": {"output": "safe"},
      "success": true,
      "score": 1
    }
  ]
}
"""

LANGFUSE_EXPORT_JSON = """\
{
  "observations": [
    {
      "id": "obs-base-1",
      "name": "baseline",
      "type": "GENERATION",
      "input": {"expected": "4", "slice": "arithmetic", "question": "2+2"},
      "output": "wrong",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-1", "slice": "arithmetic"},
      "scores": [{"name": "exact_match", "value": 0}]
    },
    {
      "id": "obs-cand-1",
      "name": "candidate",
      "type": "GENERATION",
      "input": {"expected": "4", "slice": "arithmetic", "question": "2+2"},
      "output": "4",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-1", "slice": "arithmetic"},
      "scores": [{"name": "exact_match", "value": 1}]
    },
    {
      "id": "obs-base-2",
      "name": "baseline",
      "type": "GENERATION",
      "input": {"expected": "YES", "slice": "format", "question": "Return YES"},
      "output": "NO",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-2", "slice": "format"},
      "scores": [{"name": "exact_match", "value": 0}]
    },
    {
      "id": "obs-cand-2",
      "name": "candidate",
      "type": "GENERATION",
      "input": {"expected": "YES", "slice": "format", "question": "Return YES"},
      "output": "YES",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-2", "slice": "format"},
      "scores": [{"name": "exact_match", "value": 1}]
    },
    {
      "id": "obs-base-3",
      "name": "baseline",
      "type": "GENERATION",
      "input": {"expected": "blue", "slice": "classification", "question": "Color label"},
      "output": "blue",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-3", "slice": "classification"},
      "scores": [{"name": "exact_match", "value": 1}]
    },
    {
      "id": "obs-cand-3",
      "name": "candidate",
      "type": "GENERATION",
      "input": {"expected": "blue", "slice": "classification", "question": "Color label"},
      "output": "blue",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-3", "slice": "classification"},
      "scores": [{"name": "exact_match", "value": 1}]
    },
    {
      "id": "obs-base-4",
      "name": "baseline",
      "type": "GENERATION",
      "input": {"expected": "safe", "slice": "safety", "question": "Return safe"},
      "output": "maybe",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-4", "slice": "safety"},
      "scores": [{"name": "exact_match", "value": 0}]
    },
    {
      "id": "obs-cand-4",
      "name": "candidate",
      "type": "GENERATION",
      "input": {"expected": "safe", "slice": "safety", "question": "Return safe"},
      "output": "safe",
      "model": "gpt-4o-mini-20260601",
      "metadata": {"provider": "openai", "example_id": "case-4", "slice": "safety"},
      "scores": [{"name": "exact_match", "value": 1}]
    }
  ]
}
"""

LANGSMITH_RUNS_CSV = """\
run_id,example_id,experiment_name,output,reference_output,exact_match,model,provider,slice
base-run-1,case-1,baseline,wrong,4,0,gpt-4o-mini-20260601,openai,arithmetic
base-run-2,case-2,baseline,NO,YES,0,gpt-4o-mini-20260601,openai,format
base-run-3,case-3,baseline,blue,blue,1,gpt-4o-mini-20260601,openai,classification
base-run-4,case-4,baseline,maybe,safe,0,gpt-4o-mini-20260601,openai,safety
cand-run-1,case-1,candidate,4,4,1,gpt-4o-mini-20260601,openai,arithmetic
cand-run-2,case-2,candidate,YES,YES,1,gpt-4o-mini-20260601,openai,format
cand-run-3,case-3,candidate,blue,blue,1,gpt-4o-mini-20260601,openai,classification
cand-run-4,case-4,candidate,safe,safe,1,gpt-4o-mini-20260601,openai,safety
"""

DEEPEVAL_BASELINE_JSON = """\
{
  "tool": "deepeval",
  "run_name": "baseline",
  "hyperparameters": {
    "model": "gpt-4o-mini-20260601",
    "provider": "openai"
  },
  "test_cases": [
    {
      "id": "case-1",
      "input": "What is 2 + 2?",
      "actual_output": "wrong",
      "expected_output": "4",
      "metadata": {"example_id": "case-1", "slice": "arithmetic"},
      "metrics": [{"name": "exact_match", "score": 0, "reason": "wrong answer"}]
    },
    {
      "id": "case-2",
      "input": "Return YES.",
      "actual_output": "NO",
      "expected_output": "YES",
      "metadata": {"example_id": "case-2", "slice": "format"},
      "metrics": [{"name": "exact_match", "score": 0, "reason": "wrong label"}]
    },
    {
      "id": "case-3",
      "input": "Return blue.",
      "actual_output": "blue",
      "expected_output": "blue",
      "metadata": {"example_id": "case-3", "slice": "classification"},
      "metrics": [{"name": "exact_match", "score": 1, "reason": "matches"}]
    },
    {
      "id": "case-4",
      "input": "Return safe.",
      "actual_output": "maybe",
      "expected_output": "safe",
      "metadata": {"example_id": "case-4", "slice": "safety"},
      "metrics": [{"name": "exact_match", "score": 0, "reason": "ambiguous output"}]
    }
  ]
}
"""

DEEPEVAL_CANDIDATE_JSON = """\
{
  "tool": "deepeval",
  "run_name": "candidate",
  "hyperparameters": {
    "model": "gpt-4o-mini-20260601",
    "provider": "openai"
  },
  "test_cases": [
    {
      "id": "case-1",
      "input": "What is 2 + 2?",
      "actual_output": "4",
      "expected_output": "4",
      "metadata": {"example_id": "case-1", "slice": "arithmetic"},
      "metrics": [{"name": "exact_match", "score": 1, "reason": "matches"}]
    },
    {
      "id": "case-2",
      "input": "Return YES.",
      "actual_output": "YES",
      "expected_output": "YES",
      "metadata": {"example_id": "case-2", "slice": "format"},
      "metrics": [{"name": "exact_match", "score": 1, "reason": "matches"}]
    },
    {
      "id": "case-3",
      "input": "Return blue.",
      "actual_output": "blue",
      "expected_output": "blue",
      "metadata": {"example_id": "case-3", "slice": "classification"},
      "metrics": [{"name": "exact_match", "score": 1, "reason": "matches"}]
    },
    {
      "id": "case-4",
      "input": "Return safe.",
      "actual_output": "safe",
      "expected_output": "safe",
      "metadata": {"example_id": "case-4", "slice": "safety"},
      "metrics": [{"name": "exact_match", "score": 1, "reason": "matches"}]
    }
  ]
}
"""

PROMPT_OPTIMIZER_FAVORITES_JSON = """\
{
  "version": "1.0",
  "favorites": [
    {
      "id": "strict-format",
      "title": "Strict format answer",
      "content": "Answer with exactly one JSON object and no markdown.",
      "description": "A deployment-oriented answer format prompt.",
      "tags": ["format", "deployment"],
      "category": "qa",
      "useCount": 3,
      "functionMode": "basic",
      "optimizationMode": "system",
      "metadata": {
        "originalContent": "Answer the question.",
        "sourceHistoryId": "hist-1",
        "modelKey": "openai",
        "modelName": "gpt-4o-mini",
        "templateId": "tmpl-format",
        "promptAsset": {
          "schemaVersion": "1.0",
          "currentVersionId": "v1",
          "versions": [{"id": "v1", "content": "Answer with JSON."}],
          "examples": [{"input": "2+2", "output": "{\\"answer\\":\\"4\\"}"}]
        }
      }
    },
    {
      "id": "arithmetic-check",
      "title": "Arithmetic checker",
      "content": "Solve the arithmetic problem and verify the final number.",
      "tags": ["math"],
      "functionMode": "context",
      "useCount": 1
    }
  ]
}
"""

EXTERNAL_README_MD = """\
# External Tool Export Examples

These tiny Promptfoo, Langfuse, LangSmith, DeepEval, and prompt-optimizer-style exports let you
try the external bridge without setting up those tools first.

They are intentionally small. `comparison_validity.json` may say
`needs_review` because four examples are not enough for strong statistical
evidence. That is expected: the demo proves the bridge and artifact shape, not a
universal prompt improvement claim.

DeepEval uses two files in this demo: `deepeval_baseline.json` and
`deepeval_candidate.json`.

prompt-optimizer uses `prompt_optimizer_favorites.json`. Import it with:
`pcl import prompt-optimizer --input examples/external/prompt_optimizer_favorites.json \
--out runs/from-prompt-optimizer`.
This writes prompt assets and a gap plan, not scored predictions.
"""


def write_example_project(path: Path) -> None:
    """Write a small example project."""

    ensure_dir(path / "examples")
    ensure_dir(path / "prompts")
    ensure_dir(path / "runs")
    (path / "examples" / "tasks.jsonl").write_text(TASKS_JSONL, encoding="utf-8")
    (path / "examples" / "predictions_baseline.jsonl").write_text(BASELINE_JSONL, encoding="utf-8")
    (path / "examples" / "predictions_candidate.jsonl").write_text(
        CANDIDATE_JSONL,
        encoding="utf-8",
    )
    (path / "examples" / "guard.policy.yaml").write_text(GUARD_POLICY_YAML, encoding="utf-8")
    (path / "examples" / "gate.policy.yaml").write_text(GATE_POLICY_YAML, encoding="utf-8")
    write_external_examples(path / "examples" / "external")
    (path / "prompts" / "current.txt").write_text(
        "Answer the user question exactly and keep the requested output format.\n",
        encoding="utf-8",
    )
    (path / "README.md").write_text(PROJECT_README_MD, encoding="utf-8")
    (path / "README.zh.md").write_text(PROJECT_README_ZH_MD, encoding="utf-8")
    (path / "promptcontrol.example.yaml").write_text(CONFIG_YAML, encoding="utf-8")
    (path / ".promptcontrol.yaml").write_text(PROJECT_CONFIG_YAML, encoding="utf-8")


def write_external_examples(path: Path) -> None:
    """Write bundled external-tool export examples."""

    ensure_dir(path)
    (path / "README.md").write_text(
        EXTERNAL_README_MD,
        encoding="utf-8",
    )
    (path / "promptfoo_results.json").write_text(
        PROMPTFOO_RESULTS_JSON,
        encoding="utf-8",
    )
    (path / "langfuse_export.json").write_text(
        LANGFUSE_EXPORT_JSON,
        encoding="utf-8",
    )
    (path / "langsmith_runs.csv").write_text(
        LANGSMITH_RUNS_CSV,
        encoding="utf-8",
    )
    (path / "deepeval_baseline.json").write_text(
        DEEPEVAL_BASELINE_JSON,
        encoding="utf-8",
    )
    (path / "deepeval_candidate.json").write_text(
        DEEPEVAL_CANDIDATE_JSON,
        encoding="utf-8",
    )
    (path / "prompt_optimizer_favorites.json").write_text(
        PROMPT_OPTIMIZER_FAVORITES_JSON,
        encoding="utf-8",
    )
