"""Backward-compatible facade for :mod:`promptcontrollab.integrations.ui.data`."""
# ruff: noqa: F401

from promptcontrollab.integrations.ui.data import (
    CONTROL_ARTIFACTS,
    PEOC_STATUSES,
    PROMPT_REACH_ARTIFACTS,
    RUN_ARTIFACTS,
    RUN_LEVEL_ARTIFACTS,
    audit_detail_sections,
    changed_line_rows,
    claim_check_summary,
    claim_evidence_ladder,
    control_certificate_interpretation_rows,
    decision_trace_interpretation_rows,
    deepseek_harness_view,
    ecosystem_demo_rows,
    ecosystem_evidence_matrix_rows,
    ecosystem_market_map_rows,
    ecosystem_market_readiness,
    ecosystem_scorecard_rows,
    evidence_card_rows,
    evidence_gap_action_rows,
    evidence_gap_rows,
    evidence_gate_rows,
    evidence_gate_summary,
    evidence_matrix_rows,
    external_bridge_summary,
    filter_history_rows,
    first_comparison,
    green_certificate_rows,
    guard_download_payloads,
    history_rows,
    interpretability_rows,
    list_runs,
    load_jsonl_safe,
    load_run_detail,
    model_rows,
    peoc_limitation_rows,
    peoc_method_rows,
    peoc_status_summary,
    peoc_trajectory_rows,
    posterior_certificate_metrics,
    prompt_asset_rows,
    prompt_asset_summary,
    prompt_optimizer_gap_rows,
    prompt_reach_interpretation_rows,
    redact_for_display,
    research_at_a_glance_rows,
    research_diagnostic_rows,
    research_evidence_map,
    research_gap_plan_rows,
    research_gap_script_rows,
    research_gap_status_rows,
    research_insight_rows,
    research_overview_path,
    research_status_counts,
    risk_category_counts,
    safe_display_text,
    scaffold_check_action_rows,
    scaffold_check_issue_rows,
    scaffold_check_summary,
    slice_rows,
    terminal_sensitivity_rows,
)

__all__ = [name for name in globals() if not name.startswith("_")]
