"""Static bilingual content and stable dashboard navigation constants."""
# ruff: noqa: E501,RUF001

from __future__ import annotations

DEFAULT_PRIMARY_VIEW = "before"
PRIMARY_VIEW_ORDER = (
    "before",
    "run",
    "mechanism",
    "stability",
    "training",
    "evidence",
    "decision",
    "history",
)
PRIMARY_VIEW_LABELS = {
    "en": {
        "before": "Before",
        "run": "Run",
        "mechanism": "Mechanism",
        "stability": "Stability",
        "training": "Training Gate",
        "evidence": "Evidence Scope",
        "decision": "Decision",
        "history": "History",
    },
    "zh": {
        "before": "执行前",
        "run": "运行中",
        "mechanism": "机制解释",
        "stability": "稳定性",
        "training": "训练门禁",
        "evidence": "证据边界",
        "decision": "决策",
        "history": "历史",
    },
}

HF_DEMO_TEXT = {
    "en": {
        "mode": "Public demo: CPU-only, session-isolated, and no external model calls.",
        "subtitle": (
            "Public demo artifacts are stored only in an isolated temporary server-side session; "
            "no external model requests are made."
        ),
        "upload_title": "Import a session artifact",
        "upload_help": "JSON or JSONL only, up to 5 MB. Files stay in this temporary session.",
        "upload_run": "Run name",
        "upload_button": "Validate and import",
        "upload_ok": "Imported into this session",
        "restricted": "Local write, Git, provider, plugin, bridge, and training workflows are disabled in the public demo.",
        "guard_memory": "The public demo keeps this Prompt in browser-session memory and does not save it as a server artifact.",
    },
    "zh": {
        "mode": "公共演示：仅使用 Space CPU，会话相互隔离，不调用任何外部模型。",
        "subtitle": (
            "公共演示 artifact 仅保存在隔离的临时服务器会话中；不会调用任何外部模型。"
        ),
        "upload_title": "导入当前会话的 artifact",
        "upload_help": "仅支持不超过 5 MB 的 JSON 或 JSONL；文件只保存在当前临时会话。",
        "upload_run": "Run 名称",
        "upload_button": "校验并导入",
        "upload_ok": "已导入当前会话",
        "restricted": "公共演示已禁用本地写入工作流、Git、外部 Provider、插件、Bridge 和训练功能。",
        "guard_memory": "公共演示只在浏览器会话内存中使用这条 Prompt，不会把原文保存为服务器 artifact。",
    },
}

INTERPRETATION_LABELS = {
    "en": {
        "observed": "Observed",
        "explains": "Explains",
        "does_not_prove": "Does not prove",
        "next_action": "Next action",
        "status": "Status",
        "confidence": "Confidence",
    },
    "zh": {
        "observed": "观察到了什么",
        "explains": "可以解释什么",
        "does_not_prove": "不能证明什么",
        "next_action": "下一步行动",
        "status": "状态",
        "confidence": "置信度",
    },
}
LEGACY_VIEW_GROUPS = {
    "before": ("guard", "tutorial"),
    "run": ("workflows",),
    "mechanism": (),
    "stability": ("drift", "audit"),
    "training": ("posttrain",),
    "evidence": ("research",),
    "decision": ("report",),
    "history": ("history",),
}
LEGACY_VIEW_ALIASES = {
    "guard": "before",
    "tutorial": "before",
    "workflows": "run",
    "why": "mechanism",
    "drift": "stability",
    "audit": "stability",
    "after": "stability",
    "report": "decision",
    "research": "evidence",
    "advanced": "evidence",
}

CONTROL_TEXT = {
    "en": {
        "navigation": "Primary navigation",
        "before_title": "Before execution",
        "before_caption": "Preflight and prompt-gate evidence for the selected control run.",
        "run_title": "Run evidence",
        "run_caption": "Ordered public session, turn, tool, and provider metadata.",
        "why_title": "Mechanism interpretation",
        "why_caption": "Observed factors and diagnostic associations, without causal claims.",
        "after_title": "Stability and execution evidence",
        "after_caption": "Trajectory, uncertainty, file changes, and recorded test outcomes.",
        "training_title": "Post-training checkpoint gate",
        "training_caption": "Checkpoint promotion based on performance and diagnostic evidence.",
        "evidence_title": "Evidence scope and claim boundary",
        "evidence_caption": "What is observed, what it can explain, and what remains unsupported.",
        "decision_title": "Decision",
        "decision_caption": "Current recommendation and locally available reports.",
        "advanced_title": "Evidence scope",
        "advanced_caption": (
            "PEOC and server evidence are interpreted as bounded diagnostics, not causal or "
            "safety proof."
        ),
        "missing": "No control-run artifacts are available for the selected run.",
        "run_id": "Run ID",
        "session_id": "Harness session",
        "status": "Status",
        "authorization": "Authorization",
        "agent": "Agent",
        "prompt_gate": "Prompt gate",
        "tool_gates": "Tool gates",
        "risk": "Risk",
        "review": "Review required",
        "timeline": "Session and turn timeline",
        "provider_model": "Provider and model",
        "provider": "Provider",
        "requested_model": "Requested model",
        "observed_model": "Observed model",
        "provenance": "Model provenance evidence",
        "usage": "Usage and latency",
        "input_tokens": "Input tokens",
        "output_tokens": "Output tokens",
        "total_tokens": "Total tokens",
        "cached_tokens": "Cached tokens",
        "cost": "Recorded cost",
        "latency": "Latency (ms)",
        "repeated_tools": "Repeated tool calls",
        "attribution": "Observed attribution factors",
        "guard_signals": "Harness guard signals",
        "no_guard_signals": "No Harness repeat-tool or timeout signal was recorded.",
        "stability": "Observable stability",
        "confidence": "Confidence",
        "observed_events": "Observed events",
        "signals": "Observable signal counts",
        "changes": "File and test changes",
        "recommendation": "Current recommendation",
        "reports": "Report links",
        "no_reports": "No local control report is available yet.",
        "legacy_guard": "Guard prompt",
        "legacy_tutorial": "Tutorial",
        "legacy_workflows": "Workflows",
        "legacy_drift": "Model drift",
        "legacy_audit": "Agent diff audit",
        "legacy_report": "Evaluation report",
        "legacy_research": "PEOC and research diagnostics",
    },
    "zh": {
        "navigation": "主导航",
        "before_title": "执行前",
        "before_caption": "所选 control run 的预检与 prompt gate 证据。",
        "run_title": "运行证据",
        "run_caption": "按顺序展示公开的 session、turn、工具与 provider 元数据。",
        "why_title": "机制解释",
        "why_caption": "展示可观察因素和诊断关联，不作未经验证的因果主张。",
        "after_title": "稳定性与执行证据",
        "after_caption": "展示轨迹、不确定性、文件变更与已记录测试结果。",
        "training_title": "后训练 Checkpoint 门禁",
        "training_caption": "结合性能与诊断证据判断 checkpoint 是否值得晋级。",
        "evidence_title": "证据范围与结论边界",
        "evidence_caption": "说明观察到了什么、能解释什么，以及仍然不能证明什么。",
        "decision_title": "决策",
        "decision_caption": "当前建议与本地可用报告。",
        "advanced_title": "证据边界",
        "advanced_caption": "PEOC 与服务器证据按有界诊断解释，不构成因果证明或安全证明。",
        "missing": "所选 run 暂无 control-run artifact。",
        "run_id": "Run ID",
        "session_id": "Harness session",
        "status": "状态",
        "authorization": "授权范围",
        "agent": "Agent",
        "prompt_gate": "Prompt gate",
        "tool_gates": "工具 gate",
        "risk": "风险",
        "review": "需要复核",
        "timeline": "Session 与 turn 时间线",
        "provider_model": "Provider 与模型",
        "provider": "Provider",
        "requested_model": "请求模型",
        "observed_model": "观测模型",
        "provenance": "模型来源证据",
        "usage": "Token、成本与延迟",
        "input_tokens": "输入 token",
        "output_tokens": "输出 token",
        "total_tokens": "总 token",
        "cached_tokens": "缓存 token",
        "cost": "记录成本",
        "latency": "延迟（毫秒）",
        "repeated_tools": "重复工具调用",
        "attribution": "可观察归因因素",
        "guard_signals": "Harness guard 信号",
        "no_guard_signals": "未记录 Harness 重复工具或超时信号。",
        "stability": "可观察稳定性",
        "confidence": "置信度",
        "observed_events": "观测事件数",
        "signals": "可观察信号计数",
        "changes": "文件与测试变更",
        "recommendation": "当前建议",
        "reports": "报告链接",
        "no_reports": "尚无本地 control report。",
        "legacy_guard": "Prompt 守护",
        "legacy_tutorial": "教程",
        "legacy_workflows": "工作流",
        "legacy_drift": "模型漂移",
        "legacy_audit": "Agent diff 审计",
        "legacy_report": "评测报告",
        "legacy_research": "PEOC 与研究诊断",
    },
}

TEXT = {
    "en": {
        "title": "PromptControlLab Control Runs",
        "subtitle": (
            "Local preflight, observable execution evidence, and bounded recommendations. "
            "No artifacts are uploaded."
        ),
        "research": "Research Overview",
        "research_title": "Control diagnostics for prompt optimization",
        "research_subtitle": (
            "Real PEOC bundle evidence first, followed by current-run tri-split, statistics, "
            "soft-hard, trajectory, Riccati, and time-varying control diagnostics."
        ),
        "peoc_real_title": "Imported evidence from the real PEOC replication bundle",
        "peoc_real_badge": "REAL PEOC BUNDLE",
        "peoc_manifest": "Source manifest",
        "peoc_imported_note": (
            "These are verified imported summaries from an existing PEOC replication bundle, "
            "not diagnostics freshly executed by this dashboard."
        ),
        "peoc_available": "Available",
        "peoc_partial": "Partial",
        "peoc_failed": "Failed validation",
        "peoc_unusable": "Unusable",
        "peoc_missing": "Missing",
        "peoc_full_support": "Full research support",
        "peoc_claim_scope": "Full-research claim",
        "peoc_recommendation": "Recommendation",
        "peoc_yes": "yes",
        "peoc_no": "no",
        "peoc_hard_methods": "Withheld hard-prompt method results",
        "peoc_hard_methods_note": (
            "{row_count} valid aggregate rows across {model_count} models, "
            "{task_count} tasks, and {method_count} methods. "
            "They show task-dependent outcomes, not universal optimizer superiority."
        ),
        "peoc_trajectory": "Trajectory evidence",
        "peoc_trajectory_note": (
            "The selected stationary/heterogeneous pair compares empirical decay and fit quality."
        ),
        "peoc_stage_validation": "Stage-heterogeneity validation",
        "peoc_stage_failed": (
            "Validation failed. This is retained as negative evidence and cannot support "
            "a positive stage-control claim."
        ),
        "peoc_limitations": "Missing, unusable, or failed evidence",
        "peoc_report": "Detailed bounded case study",
        "peoc_report_guidance": (
            "Open research_case_study.html from this run directory for the complete local report."
        ),
        "research_empty": "No research diagnostics found for this run.",
        "research_demo_command": "pcl research-quickstart --out runs/research-demo --open-report",
        "research_pipeline": "Research workflow",
        "research_at_a_glance": "At a glance",
        "research_overview_graphic": "Research overview graphic",
        "research_insights": "Plain-language interpretation",
        "research_evidence_map": "Research evidence map",
        "research_diagnostics": "Fresh current-run diagnostics",
        "research_coverage": "Fresh diagnostic coverage",
        "paper_protocol": "Protocol hygiene",
        "diagnostic_coverage": "Diagnostics ready",
        "artifact_evidence": "Evidence artifacts",
        "evidence_card": "Evidence card",
        "evidence_card_missing": "No evidence_card.json found yet.",
        "evidence_card_command": "pcl evidence-card --run <selected-run>",
        "evidence_gate": "Evidence gate",
        "evidence_gate_missing": "No evidence_gate_result.json found yet.",
        "evidence_gate_command": "pcl evidence-gate --run <selected-run> --strict",
        "evidence_gate_status": "Evidence gate status",
        "evidence_gate_required": "Required checks",
        "claim_check": "Claim check",
        "claim_ladder": "Evidence ladder",
        "claim_check_missing": "No claim_check.json found yet.",
        "claim_check_command": "pcl claim-check --run <selected-run> --claim full-research",
        "claim_check_status": "Claim status",
        "claim_check_requested": "Requested claim",
        "claim_check_tier": "Evidence tier",
        "claim_check_safe": "Safe claim",
        "claim_check_reason": "Reason",
        "claim_check_next_missing": "Missing for next tier",
        "ecosystem_bridge": "Ecosystem bridge",
        "ecosystem_scorecard": "Ecosystem scorecard",
        "ecosystem_evidence_matrix": "PCL-added evidence matrix",
        "ecosystem_market_readiness": "Market readiness",
        "ecosystem_market_readiness_note": (
            "Action summary from the positioning matrix: where PCL should lead, learn, "
            "and avoid overbuilding."
        ),
        "ecosystem_market_map": "Extended market map",
        "ecosystem_market_map_note": (
            "Positioning references only; these rows are not imported evidence bundles."
        ),
        "ecosystem_demo": "Ecosystem demo bundles",
        "prompt_assets": "Prompt optimizer assets",
        "prompt_assets_summary": "Imported prompt candidates",
        "prompt_assets_gap_plan": "Evidence gaps before claiming improvement",
        "prompt_assets_missing": "No prompt-optimizer asset import found.",
        "scaffold_check": "Eval scaffold check",
        "scaffold_check_missing": "No scaffold_check.json found yet.",
        "scaffold_check_command": "pcl scaffold-check --run <selected-run>",
        "scaffold_status": "Scaffold status",
        "scaffold_issues": "Scaffold issues",
        "scaffold_next_actions": "Scaffold next actions",
        "evidence_gap_diagnosis": "Paper evidence gap diagnosis",
        "evidence_gap_actions": "How to close these gaps",
        "research_gap_plan": "Research gap plan",
        "research_gap_scripts": "Review-first command scripts",
        "research_gap_status": "Research gap closure status",
        "ecosystem_bridge_missing": "No external evidence bridge artifact found.",
        "external_tools": "External tools",
        "pcl_added_evidence": "PCL-added evidence",
        "missing_evidence": "Missing evidence",
        "bridge_next_actions": "Bridge next actions",
        "evidence_recommendation": "Evidence recommendation",
        "evidence_summary": "Evidence summary",
        "evidence_sections": "Evidence card sections",
        "hidden_state_input": "Hidden-state input",
        "research_boundary": (
            "These diagnostics make prompt experiments easier to inspect. They are not "
            "a proof of full language-model stability or universal prompt improvement."
        ),
        "tri_split": "Tri-split",
        "paired_stats": "Paired stats",
        "soft_hard": "Soft-hard",
        "trajectory_diag": "Trajectory",
        "riccati_diag": "Riccati",
        "tv_soft_diag": "TV-soft",
        "runs": "Runs directory",
        "policy": "Guard policy",
        "guard": "Guard Prompt",
        "workflows": "Workflows",
        "tutorial": "Tutorial",
        "tutorial_intro": (
            "Follow the cards below from top to bottom. Each card shows what to do, "
            "what artifact you get, what the result means, and what to do next."
        ),
        "tutorial_framework_note": "",
        "tutorial_operation": "Operation",
        "tutorial_result": "What you get",
        "tutorial_meaning": "What it means",
        "tutorial_next_step": "Next step",
        "tutorial_command": "CLI equivalent",
        "tutorial_steps": "Steps",
        "onboarding_title": "Choose the fastest path",
        "onboarding_goal": "Goal",
        "onboarding_start": "Start here",
        "onboarding_next": "Then",
        "ecosystem_choice_title": "Which tool should I use first?",
        "ecosystem_choice_start": "Starting point",
        "ecosystem_choice_use": "Use first",
        "ecosystem_choice_add": "Add PCL when...",
        "tool_choice_need": "Describe your need",
        "tool_choice_placeholder": "security evals, prompt writing, observability, research evidence...",
        "tool_choice_recommendation": "Recommendation",
        "tool_choice_why": "Why",
        "tool_choice_commands": "Suggested PCL commands",
        "tool_choice_avoid": "Avoid",
        "tool_choice_gap_actions": "From market gap to PCL command",
        "tool_choice_gap_input": "External result",
        "tool_choice_gap_gap": "Evidence gap",
        "tool_choice_gap_command": "Run next",
        "tool_choice_gap_open": "Open first",
        "tool_choice_download_json": "Download tool_choice.json",
        "tool_choice_download_md": "Download tool_choice.md",
        "adoption_path_title": "Five-minute adoption path",
        "adoption_path_minute": "Minute",
        "adoption_path_action": "Do this",
        "adoption_path_result": "You should get",
        "execution_mode": "Execution mode",
        "overwrite": "Overwrite existing artifacts",
        "allow_external_outputs": "Allow writing outside runs directory",
        "write_boundary": (
            "Workflow writes should stay under the selected runs directory. "
            "External output paths are warned and blocked in auto mode unless explicitly allowed."
        ),
        "confirm_write": "Confirm write",
        "run_action": "Run",
        "create_demo": "Create demo artifacts",
        "workflow_preview": "Preview",
        "workflow_result": "Workflow result",
        "guard_workflow": "Guard prompt",
        "analyze_workflow": "Run analyze",
        "gate_workflow": "Run gate",
        "evidence_card_workflow": "Build evidence card",
        "import_workflow": "Import external run",
        "external_evidence_workflow": "External evidence bundle",
        "audit_workflow": "Run audit-diff",
        "agent_run_workflow": "Build agent-run",
        "pr_summary_workflow": "Generate PR summary",
        "export_workflow": "Export report zip",
        "external_tool": "External tool",
        "external_input": "External export",
        "baseline_input": "Baseline export",
        "candidate_input": "Candidate export",
        "score_name": "Score name",
        "provider": "Provider",
        "model": "Model",
        "prompt_id": "Prompt ID",
        "name_filter": "Name filter",
        "experiment_filter": "Experiment filter",
        "asset_id": "Asset ID",
        "method": "Method",
        "baseline_prompt_id": "Baseline prompt ID",
        "candidate_prompt_id": "Candidate prompt ID",
        "baseline_name": "Baseline name",
        "candidate_name": "Candidate name",
        "baseline_experiment": "Baseline experiment",
        "candidate_experiment": "Candidate experiment",
        "split_hash": "Split hash",
        "bootstrap_samples": "Bootstrap samples",
        "permutation_samples": "Permutation samples",
        "out_dir": "Output directory",
        "data_path": "Task JSONL",
        "baseline_predictions": "Baseline predictions",
        "candidate_predictions": "Candidate predictions",
        "metric": "Metric",
        "policy_path": "Policy path",
        "run_dir": "Run directory",
        "repo": "Repository",
        "before": "Before ref",
        "after": "After ref",
        "tests_run": "Recorded tests",
        "audit_dir": "Audit directory",
        "agent": "Agent",
        "agent_run_path": "agent_run.json path",
        "markdown_path": "Markdown path",
        "json_path": "JSON path",
        "zip_path": "Zip path",
        "report": "Run Report",
        "drift": "Model Drift",
        "audit": "Agent Diff Audit",
        "history": "History",
        "prompt": "Prompt",
        "run_guard": "Run guard",
        "selected_run": "Selected run",
        "missing_run": "No run directories found.",
        "empty_run": "This run has no recognized artifacts.",
        "decision": "Decision",
        "risk": "Risk",
        "review": "Required review",
        "categories": "Risk categories",
        "violations": "Policy violations",
        "token_cost": "Estimated token cost",
        "diff": "Prompt diff",
        "recommendation": "Recommendation",
        "gate": "Gate status",
        "candidate_score": "Candidate score",
        "comparison_validity": "Comparison validity",
        "prompt_only": "Prompt-only",
        "mean_delta": "Mean delta",
        "p_value": "p-value",
        "model_provenance": "Model provenance",
        "drift_risk": "Drift risk",
        "audit_review": "Human review required",
        "dangerous_paths": "Dangerous paths",
        "changed_files": "Changed files",
        "profile": "Profile",
        "mode": "Mode",
        "token_mode": "Token mode",
        "max_tokens": "Max tokens",
        "guarded_prompt": "Guarded prompt",
        "save_guard": "Save guard artifacts",
        "save_guard_dir": "Guard save directory",
        "saved_guard": "Saved guard artifacts",
        "download_guard_json": "Download guard_result.json",
        "download_improved_prompt": "Download improved_prompt.txt",
        "risk_chart": "Risk Categories",
        "count": "count",
        "category": "category",
        "none": "none",
        "score_ci": "Score Delta CI",
        "slice_scores": "Slice Scores",
        "baseline": "baseline",
        "candidate": "candidate",
        "model_timeline": "Model timeline",
        "no_model": "No model provenance recorded.",
        "no_audit": "No audit_result.json found.",
        "public_api": "Public API",
        "tests_passed": "Tests passed",
        "file_breakdown": "Touched Files Breakdown",
        "file_kind": "kind",
        "source_files": "source",
        "test_files": "tests",
        "docs_files": "docs",
        "config_files": "config",
        "path": "path",
        "no_history": "No history_index.json found.",
        "run_timeline": "Run timeline",
        "gate_trend": "Gate trend",
        "score_trend": "Score trend",
        "risk_trend": "Risk trend",
        "review_trend": "Review trend",
        "prompt_identity": "Prompt identity",
        "model_changes": "Model/provider changes",
        "audit_details": "Audit details",
        "secret_findings": "Secret findings",
        "dependency_files": "Dependency files",
        "lockfiles": "Lockfiles",
        "workflow_files": "Workflow files",
        "deleted_test_files": "Deleted test files",
        "unexpected_files": "Unexpected files",
        "test_results": "Test results",
        "changed_lines": "Changed lines",
        "file": "file",
        "added": "added",
        "deleted": "deleted",
        "only_review_required": "Only review-required runs",
        "only_high_risk": "Only high-risk runs",
        "provider_filter": "Provider filter",
        "model_filter": "Model filter",
        "risk_categories": "Risk categories",
    },
    "zh": {
        "title": "PromptControlLab Control Runs",
        "subtitle": "本地预检、可观察执行证据和有边界的建议。不会上传 prompt、代码或 artifact。",
        "research": "研究总览",
        "research_title": "Prompt 优化的控制论诊断工作台",
        "research_subtitle": (
            "先看真实 PEOC 复现包证据，再查看当前 run 的三段切分、成对统计、软转硬、"
            "轨迹、Riccati 和时变控制诊断。"
        ),
        "peoc_real_title": "从真实 PEOC 复现包导入的研究证据",
        "peoc_real_badge": "真实 PEOC 证据包",
        "peoc_manifest": "来源清单",
        "peoc_imported_note": (
            "这里展示的是经过校验后导入的既有 PEOC 复现实验摘要，"
            "不是本仪表盘刚刚重新运行出的诊断。"
        ),
        "peoc_available": "可用",
        "peoc_partial": "部分可用",
        "peoc_failed": "验证失败",
        "peoc_unusable": "不可用",
        "peoc_missing": "缺失",
        "peoc_full_support": "完整研究支持",
        "peoc_claim_scope": "完整研究主张",
        "peoc_recommendation": "建议",
        "peoc_yes": "是",
        "peoc_no": "否",
        "peoc_hard_methods": "Withheld hard prompt 方法结果",
        "peoc_hard_methods_note": (
            "共 {row_count} 条有效汇总记录，覆盖 {model_count} 个模型、"
            "{task_count} 个任务和 {method_count} 种方法。"
            "结果随任务变化，不能说明某一种优化器普遍更好。"
        ),
        "peoc_trajectory": "轨迹证据",
        "peoc_trajectory_note": "选中的平稳/异质任务对比展示经验衰减率和拟合质量。",
        "peoc_stage_validation": "阶段异质性验证",
        "peoc_stage_failed": (
            "该验证没有通过。系统将它保留为负面证据，不能用来支持正向的阶段控制主张。"
        ),
        "peoc_limitations": "缺失、不可用或验证失败的证据",
        "peoc_report": "完整边界化案例报告",
        "peoc_report_guidance": (
            "请在当前 run 目录中打开 research_case_study.html，查看完整本地报告。"
        ),
        "research_empty": "当前 run 还没有研究诊断 artifact。",
        "research_demo_command": (
            "pcl research-quickstart --out runs/research-demo --language zh --open-report"
        ),
        "research_pipeline": "研究流程",
        "research_at_a_glance": "一眼看懂",
        "research_overview_graphic": "研究总览图",
        "research_insights": "直白解释",
        "research_evidence_map": "研究证据地图",
        "research_diagnostics": "当前 run 新执行的诊断",
        "research_coverage": "新执行诊断覆盖情况",
        "paper_protocol": "协议洁净度",
        "diagnostic_coverage": "已完成诊断",
        "artifact_evidence": "证据 artifact",
        "evidence_card": "证据卡",
        "evidence_card_missing": "当前还没有 evidence_card.json。",
        "evidence_card_command": "pcl evidence-card --run <选中的 run>",
        "evidence_gate": "证据门禁",
        "evidence_gate_missing": "当前还没有 evidence_gate_result.json。",
        "evidence_gate_command": "pcl evidence-gate --run <选中的 run> --strict",
        "evidence_gate_status": "证据门禁状态",
        "evidence_gate_required": "必要检查",
        "claim_check": "主张检查",
        "claim_ladder": "证据阶梯",
        "claim_check_missing": "当前还没有 claim_check.json。",
        "claim_check_command": "pcl claim-check --run <选中的 run> --claim full-research",
        "claim_check_status": "主张状态",
        "claim_check_requested": "请求主张",
        "claim_check_tier": "证据层级",
        "claim_check_safe": "安全主张",
        "claim_check_reason": "原因",
        "claim_check_next_missing": "下一层级缺失证据",
        "ecosystem_bridge": "生态桥接",
        "ecosystem_scorecard": "生态证据总览",
        "ecosystem_evidence_matrix": "PCL 补充证据矩阵",
        "ecosystem_market_readiness": "市场就绪度",
        "ecosystem_market_readiness_note": (
            "从定位矩阵提炼出的行动摘要：PCL 应该领先什么、学习什么、避免重复建设什么。"
        ),
        "ecosystem_market_map": "扩展市场地图",
        "ecosystem_market_map_note": "仅作定位参考；这些行不是已导入的证据包。",
        "ecosystem_demo": "生态 demo 证据包",
        "prompt_assets": "Prompt optimizer 资产",
        "prompt_assets_summary": "已导入的 prompt 候选",
        "prompt_assets_gap_plan": "声称优化有效前缺少的证据",
        "prompt_assets_missing": "当前还没有 prompt-optimizer 资产导入 artifact。",
        "scaffold_check": "评测 scaffold 检查",
        "scaffold_check_missing": "当前还没有 scaffold_check.json。",
        "scaffold_check_command": "pcl scaffold-check --run <选中的 run>",
        "scaffold_status": "Scaffold 状态",
        "scaffold_issues": "Scaffold 问题",
        "scaffold_next_actions": "Scaffold 下一步",
        "evidence_gap_diagnosis": "论文证据缺口诊断",
        "evidence_gap_actions": "如何补齐这些缺口",
        "research_gap_plan": "研究证据缺口计划",
        "research_gap_scripts": "Review-first 命令脚本",
        "research_gap_status": "研究缺口补齐状态",
        "ecosystem_bridge_missing": "当前还没有外部证据桥接 artifact。",
        "external_tools": "外部工具",
        "pcl_added_evidence": "PCL 补充证据",
        "missing_evidence": "缺失证据",
        "bridge_next_actions": "桥接后下一步",
        "evidence_recommendation": "证据推荐",
        "evidence_summary": "证据摘要",
        "evidence_sections": "证据卡分段",
        "hidden_state_input": "hidden-state 输入",
        "research_boundary": (
            "这些诊断让 prompt 实验更容易被检查和复现，但它们不是完整语言模型稳定性"
            "或通用 prompt 提升的数学证明。"
        ),
        "tri_split": "三段切分",
        "paired_stats": "成对统计",
        "soft_hard": "软转硬",
        "trajectory_diag": "轨迹诊断",
        "riccati_diag": "Riccati",
        "tv_soft_diag": "TV-soft",
        "runs": "Runs 目录",
        "policy": "Guard 策略",
        "guard": "Prompt 守护",
        "workflows": "工作流",
        "tutorial": "教程",
        "tutorial_intro": (
            "建议从上到下阅读。每个卡片都会说明：怎么操作、会得到什么文件、"
            "这个结果说明什么问题，以及下一步该怎么做。"
        ),
        "tutorial_framework_note": "",
        "tutorial_operation": "操作",
        "tutorial_result": "得到什么",
        "tutorial_meaning": "说明什么问题",
        "tutorial_next_step": "下一步",
        "tutorial_command": "CLI 等价命令",
        "tutorial_steps": "操作步骤",
        "onboarding_title": "先选最快路径",
        "onboarding_goal": "目标",
        "onboarding_start": "从这里开始",
        "onboarding_next": "然后",
        "ecosystem_choice_title": "我应该先用哪个工具？",
        "ecosystem_choice_start": "你的起点",
        "ecosystem_choice_use": "先用",
        "ecosystem_choice_add": "什么时候加入 PCL",
        "tool_choice_need": "描述你的目标",
        "tool_choice_placeholder": "安全评测、prompt 写作、观测、研究证据……",
        "tool_choice_recommendation": "推荐",
        "tool_choice_why": "为什么",
        "tool_choice_commands": "建议使用的 PCL 命令",
        "tool_choice_avoid": "不要做",
        "tool_choice_gap_actions": "从市场缺口到 PCL 命令",
        "tool_choice_gap_input": "外部结果",
        "tool_choice_gap_gap": "证据缺口",
        "tool_choice_gap_command": "下一步运行",
        "tool_choice_gap_open": "先打开",
        "tool_choice_download_json": "下载 tool_choice.json",
        "tool_choice_download_md": "下载 tool_choice.md",
        "adoption_path_title": "5 分钟采用路径",
        "adoption_path_minute": "分钟",
        "adoption_path_action": "操作",
        "adoption_path_result": "应该得到什么",
        "execution_mode": "执行模式",
        "overwrite": "覆盖已有 artifact",
        "allow_external_outputs": "允许写入 runs 目录之外",
        "write_boundary": (
            "工作流默认应写入当前 runs 目录下。"
            "外部输出路径会提示风险, 并在 auto 模式下被阻止, 除非显式允许。"
        ),
        "confirm_write": "确认写入",
        "run_action": "运行",
        "create_demo": "创建 demo artifact",
        "workflow_preview": "预览",
        "workflow_result": "工作流结果",
        "guard_workflow": "守护 Prompt",
        "analyze_workflow": "运行 analyze",
        "gate_workflow": "运行 gate",
        "evidence_card_workflow": "生成证据卡",
        "import_workflow": "导入外部 run",
        "external_evidence_workflow": "生成外部证据包",
        "audit_workflow": "运行 audit-diff",
        "agent_run_workflow": "生成 agent-run",
        "pr_summary_workflow": "生成 PR summary",
        "export_workflow": "导出报告 zip",
        "external_tool": "外部工具",
        "external_input": "外部导出文件",
        "baseline_input": "Baseline 导出文件",
        "candidate_input": "Candidate 导出文件",
        "score_name": "分数字段名",
        "provider": "Provider",
        "model": "模型",
        "prompt_id": "Prompt ID",
        "name_filter": "Name 过滤",
        "experiment_filter": "Experiment 过滤",
        "asset_id": "Asset ID",
        "method": "Method",
        "baseline_prompt_id": "Baseline prompt ID",
        "candidate_prompt_id": "Candidate prompt ID",
        "baseline_name": "Baseline 名称",
        "candidate_name": "Candidate 名称",
        "baseline_experiment": "Baseline 实验名",
        "candidate_experiment": "Candidate 实验名",
        "split_hash": "Split hash",
        "bootstrap_samples": "Bootstrap 采样数",
        "permutation_samples": "Permutation 采样数",
        "out_dir": "输出目录",
        "data_path": "任务 JSONL",
        "baseline_predictions": "Baseline predictions",
        "candidate_predictions": "Candidate predictions",
        "metric": "指标",
        "policy_path": "策略路径",
        "run_dir": "Run 目录",
        "repo": "仓库",
        "before": "Before ref",
        "after": "After ref",
        "tests_run": "已记录测试",
        "audit_dir": "Audit 目录",
        "agent": "Agent",
        "agent_run_path": "agent_run.json 路径",
        "markdown_path": "Markdown 路径",
        "json_path": "JSON 路径",
        "zip_path": "Zip 路径",
        "report": "运行报告",
        "drift": "模型漂移",
        "audit": "Agent 改动审计",
        "history": "历史",
        "prompt": "提示词",
        "run_guard": "运行守护",
        "selected_run": "选择 run",
        "missing_run": "没有找到 run 目录。",
        "empty_run": "这个 run 没有识别到 artifact。",
        "decision": "决策",
        "risk": "风险",
        "review": "需要人工复核",
        "categories": "风险类别",
        "violations": "策略违规",
        "token_cost": "估算 token 成本",
        "diff": "Prompt 差异",
        "recommendation": "部署建议",
        "gate": "门禁状态",
        "candidate_score": "候选分数",
        "comparison_validity": "比较有效性",
        "prompt_only": "Prompt-only",
        "mean_delta": "均值差异",
        "p_value": "p-value",
        "model_provenance": "模型来源",
        "drift_risk": "漂移风险",
        "audit_review": "需要人工复核",
        "dangerous_paths": "危险路径",
        "changed_files": "改动文件",
        "profile": "场景",
        "mode": "模式",
        "token_mode": "Token 模式",
        "max_tokens": "最大 Token",
        "guarded_prompt": "守护后的提示词",
        "save_guard": "保存 guard artifact",
        "save_guard_dir": "Guard 保存目录",
        "saved_guard": "已保存 guard artifact",
        "download_guard_json": "下载 guard_result.json",
        "download_improved_prompt": "下载 improved_prompt.txt",
        "risk_chart": "风险类别",
        "count": "数量",
        "category": "类别",
        "none": "无",
        "score_ci": "分数差异置信区间",
        "slice_scores": "任务切片分数",
        "baseline": "基线",
        "candidate": "候选",
        "model_timeline": "模型时间线",
        "no_model": "没有记录模型来源。",
        "no_audit": "没有找到 audit_result.json。",
        "public_api": "公共 API",
        "tests_passed": "测试通过",
        "file_breakdown": "改动文件类型",
        "file_kind": "类型",
        "source_files": "源码",
        "test_files": "测试",
        "docs_files": "文档",
        "config_files": "配置",
        "path": "路径",
        "no_history": "没有找到 history_index.json。",
        "run_timeline": "Run 时间线",
        "gate_trend": "门禁趋势",
        "score_trend": "分数趋势",
        "risk_trend": "风险趋势",
        "review_trend": "复核趋势",
        "prompt_identity": "Prompt 身份",
        "model_changes": "模型 / provider 变化",
        "audit_details": "审计明细",
        "secret_findings": "疑似密钥",
        "dependency_files": "依赖文件",
        "lockfiles": "锁文件",
        "workflow_files": "Workflow 文件",
        "deleted_test_files": "删除的测试文件",
        "unexpected_files": "意外文件",
        "test_results": "测试结果",
        "changed_lines": "改动行数",
        "file": "文件",
        "added": "新增",
        "deleted": "删除",
        "only_review_required": "只看需要复核的 run",
        "only_high_risk": "只看高风险 run",
        "provider_filter": "Provider 过滤",
        "model_filter": "模型过滤",
        "risk_categories": "风险类别",
    },
}

CHOICE_OPTIONS = {
    "execution_mode": [
        ("confirm", "confirm", "确认后执行"),
        ("auto", "auto", "自动执行"),
        ("command", "command", "只生成命令"),
    ],
    "profile": [
        ("coding", "coding", "编程"),
        ("general", "general", "通用"),
        ("research", "research", "研究"),
    ],
    "guard_mode": [
        ("suggest", "suggest", "给出建议"),
        ("auto", "auto", "自动改写"),
        ("gate", "gate", "门禁检查"),
    ],
    "token_mode": [
        ("balanced", "balanced", "平衡省 token"),
        ("aggressive", "aggressive", "激进省 token"),
    ],
    "tests_passed": [
        ("unknown", "unknown", "未知"),
        ("true", "true", "通过"),
        ("false", "false", "失败"),
    ],
    "external_tool": [
        ("auto", "auto", "自动识别"),
        ("promptfoo", "promptfoo", "Promptfoo"),
        ("langfuse", "langfuse", "Langfuse"),
        ("langsmith", "langsmith", "LangSmith"),
        ("deepeval", "deepeval", "DeepEval"),
    ],
    "import_tool": [
        ("auto", "auto", "自动识别"),
        ("promptfoo", "promptfoo", "Promptfoo"),
        ("langfuse", "langfuse", "Langfuse"),
        ("langsmith", "langsmith", "LangSmith"),
        ("deepeval", "deepeval", "DeepEval"),
        ("prompt-optimizer", "prompt-optimizer", "prompt-optimizer"),
    ],
}


TEXT["zh"].update(
    {
        "title": "prompt_control_lab 本地仪表盘",
        "subtitle": "本地执行前检查、模型溯源和 agent 审计视图。不会上传 prompt、代码或 artifact。",
        "runs": "Runs 目录",
        "policy": "Guard 策略",
        "guard": "Prompt 守护",
        "workflows": "工作流",
        "tutorial": "教程",
        "tutorial_intro": "建议从上到下阅读。每个卡片都会说明：怎么操作、会得到什么文件、结果说明什么问题，以及下一步怎么做。",
        "tutorial_framework_note": "",
        "tutorial_operation": "操作",
        "tutorial_result": "得到什么",
        "tutorial_meaning": "说明什么问题",
        "tutorial_next_step": "下一步",
        "tutorial_command": "CLI 等价命令",
        "onboarding_title": "先选最快路径",
        "onboarding_goal": "目标",
        "onboarding_start": "从这里开始",
        "onboarding_next": "然后",
        "execution_mode": "执行模式",
        "overwrite": "覆盖已有 artifact",
        "allow_external_outputs": "允许写入 runs 目录之外",
        "write_boundary": "工作流默认应该写入当前 runs 目录下。外部输出路径会提示风险，并在自动执行模式下被阻止，除非显式允许。",
        "confirm_write": "确认写入",
        "run_action": "运行",
        "create_demo": "创建演示数据",
        "workflow_preview": "预览",
        "workflow_result": "工作流结果",
        "guard_workflow": "守护 Prompt",
        "analyze_workflow": "运行 analyze",
        "gate_workflow": "运行 gate",
        "audit_workflow": "运行 audit-diff",
        "agent_run_workflow": "生成 agent-run",
        "pr_summary_workflow": "生成 PR summary",
        "export_workflow": "导出报告 zip",
        "out_dir": "输出目录",
        "data_path": "任务 JSONL",
        "baseline_predictions": "Baseline 预测文件",
        "candidate_predictions": "Candidate 预测文件",
        "metric": "指标",
        "policy_path": "策略路径",
        "run_dir": "Run 目录",
        "repo": "仓库",
        "before": "Before ref",
        "after": "After ref",
        "tests_run": "已记录测试",
        "audit_dir": "Audit 目录",
        "agent": "Agent",
        "agent_run_path": "agent_run.json 路径",
        "markdown_path": "Markdown 路径",
        "json_path": "JSON 路径",
        "zip_path": "Zip 路径",
        "report": "运行报告",
        "drift": "模型漂移",
        "audit": "Agent 改动审计",
        "history": "历史",
        "prompt": "提示词",
        "run_guard": "运行守护",
        "selected_run": "选择 run",
        "missing_run": "没有找到 run 目录。",
        "empty_run": "这个 run 没有识别到 artifact。",
        "decision": "决策",
        "risk": "风险",
        "review": "需要人工复核",
        "categories": "风险类别",
        "violations": "策略违规",
        "token_cost": "估算 token 成本",
        "diff": "Prompt 差异",
        "recommendation": "部署建议",
        "gate": "门禁状态",
        "candidate_score": "候选分数",
        "comparison_validity": "比较有效性",
        "prompt_only": "Prompt-only",
        "mean_delta": "均值差异",
        "p_value": "p-value",
        "model_provenance": "模型来源",
        "drift_risk": "漂移风险",
        "audit_review": "需要人工复核",
        "dangerous_paths": "危险路径",
        "changed_files": "改动文件",
        "profile": "场景",
        "mode": "模式",
        "token_mode": "Token 模式",
        "max_tokens": "最大 Token",
        "guarded_prompt": "守护后的提示词",
        "save_guard": "保存 guard artifact",
        "save_guard_dir": "Guard 保存目录",
        "saved_guard": "已保存 guard artifact",
        "download_guard_json": "下载 guard_result.json",
        "download_improved_prompt": "下载 improved_prompt.txt",
        "risk_chart": "风险类别",
        "count": "数量",
        "category": "类别",
        "none": "无",
        "score_ci": "分数差异置信区间",
        "slice_scores": "任务切片分数",
        "baseline": "基线",
        "candidate": "候选",
        "model_timeline": "模型时间线",
        "no_model": "没有记录模型来源。",
        "no_audit": "没有找到 audit_result.json。",
        "public_api": "公共 API",
        "tests_passed": "测试通过",
        "file_breakdown": "改动文件类型",
        "file_kind": "类型",
        "source_files": "源码",
        "test_files": "测试",
        "docs_files": "文档",
        "config_files": "配置",
        "path": "路径",
        "no_history": "没有找到 history_index.json。",
        "run_timeline": "Run 时间线",
        "gate_trend": "门禁趋势",
        "score_trend": "分数趋势",
        "risk_trend": "风险趋势",
        "review_trend": "复核趋势",
        "prompt_identity": "Prompt 身份",
        "model_changes": "模型 / provider 变化",
        "audit_details": "审计明细",
        "secret_findings": "疑似密钥",
        "dependency_files": "依赖文件",
        "lockfiles": "锁文件",
        "workflow_files": "Workflow 文件",
        "deleted_test_files": "删除的测试文件",
        "unexpected_files": "意外文件",
        "test_results": "测试结果",
        "changed_lines": "改动行数",
        "file": "文件",
        "added": "新增",
        "deleted": "删除",
        "only_review_required": "只看需要复核的 run",
        "only_high_risk": "只看高风险 run",
        "provider_filter": "Provider 过滤",
        "model_filter": "模型过滤",
        "risk_categories": "风险类别",
    }
)

CHOICE_OPTIONS.update(
    {
        "execution_mode": [
            ("confirm", "confirm", "确认后执行"),
            ("auto", "auto", "自动执行"),
            ("command", "command", "只生成命令"),
        ],
        "profile": [
            ("coding", "coding", "编程"),
            ("general", "general", "通用"),
            ("research", "research", "研究"),
        ],
        "guard_mode": [
            ("suggest", "suggest", "给出建议"),
            ("auto", "auto", "自动改写"),
            ("gate", "gate", "门禁检查"),
        ],
        "token_mode": [
            ("balanced", "balanced", "平衡省 token"),
            ("aggressive", "aggressive", "激进省 token"),
        ],
        "tests_passed": [
            ("unknown", "unknown", "未知"),
            ("true", "true", "通过"),
            ("false", "false", "失败"),
        ],
        "external_tool": [
            ("auto", "auto", "自动识别"),
            ("promptfoo", "promptfoo", "Promptfoo"),
            ("langfuse", "langfuse", "Langfuse"),
            ("langsmith", "langsmith", "LangSmith"),
            ("deepeval", "deepeval", "DeepEval"),
        ],
        "import_tool": [
            ("auto", "auto", "自动识别"),
            ("promptfoo", "promptfoo", "Promptfoo"),
            ("langfuse", "langfuse", "Langfuse"),
            ("langsmith", "langsmith", "LangSmith"),
            ("deepeval", "deepeval", "DeepEval"),
            ("prompt-optimizer", "prompt-optimizer", "prompt-optimizer"),
        ],
    }
)
