"""Static bilingual tutorial, onboarding, and screenshot content."""
# ruff: noqa: E501,RUF001

from __future__ import annotations

TUTORIAL_IMAGES = {
    "overview": ("tutorial_overview.svg", "tutorial_overview.zh.svg"),
    "guard": ("tutorial_guard.svg", "tutorial_guard.zh.svg"),
    "report": ("tutorial_report.svg", "tutorial_report.zh.svg"),
    "audit_history": ("tutorial_audit_history.svg", "tutorial_audit_history.zh.svg"),
}

TUTORIAL_SCREENSHOTS = {
    "workflows": ("tutorial_workflows.en.png", "tutorial_workflows.zh.png"),
    "guard": ("tutorial_guard.en.png", "tutorial_guard.zh.png"),
    "report": ("tutorial_report.en.png", "tutorial_report.zh.png"),
    "model_drift": ("tutorial_model_drift.en.png", "tutorial_model_drift.zh.png"),
    "audit": ("tutorial_audit.en.png", "tutorial_audit.zh.png"),
    "history": ("tutorial_history.en.png", "tutorial_history.zh.png"),
}

TUTORIAL_SECTION_SCREENSHOTS = {
    "guard": "guard",
    "workflows": "workflows",
    "report": "report",
    "drift": "model_drift",
    "audit": "audit",
    "history": "history",
    "import_external": "workflows",
    "project_defaults": "workflows",
    "export_pr": "workflows",
}

TUTORIAL_STEPS = {
    "en": {
        "guard": [
            "Open the Guard Prompt tab.",
            "Paste the prompt the agent would run.",
            "Choose the coding profile and your guard policy.",
            "Click Run guard, then read the decision, risk categories, and improved prompt.",
        ],
        "workflows": [
            "Open the Workflows tab.",
            "Keep Execution mode on confirm for the first run.",
            "Click Create demo artifacts and confirm the files that will be written.",
            "Use the generated run in Run Report, Audit, and History.",
        ],
        "import_external": [
            "Open Workflows and expand Import external run.",
            "Choose auto, Promptfoo, Langfuse, LangSmith, DeepEval, or prompt-optimizer.",
            "Select the export file and output directory, then run in confirm mode first.",
            "Open the generated run, evidence card, scaffold check, or prompt asset gap plan.",
        ],
        "report": [
            "Select a run in the sidebar.",
            "Open Run Report.",
            "Read the recommendation, gate status, score delta, confidence interval, and model provenance.",
            "Use fixed or broken examples to decide what to inspect next.",
        ],
        "drift": [
            "Open Model Drift after selecting a run.",
            "Check baseline and candidate provider/model values.",
            "If drift is unknown, run model-drift between two run directories.",
            "Treat model mismatch as a comparison-validity warning.",
        ],
        "audit": [
            "Run audit-diff after an agent changes the repository.",
            "Open Agent Diff Audit and inspect touched files, changed lines, and dangerous paths.",
            "Check dependency, workflow, secret-like, deleted-test, and unexpected-file sections.",
            "Require human review before merging high-risk changes.",
        ],
        "history": [
            "Run history index over the runs directory.",
            "Open History and filter by review-required, high-risk, provider, or model.",
            "Read score, gate, risk, and model trends together.",
            "Use the table to open the run that needs attention.",
        ],
        "project_defaults": [
            "Create or edit .promptcontrol.yaml at the repository root.",
            "Set guard_policy, gate_policy, runs_dir, expected_paths, and test_commands.",
            "Restart or refresh the UI so sidebar defaults reflect the project file.",
            "Override any default from the CLI or UI when a run needs a one-off value.",
        ],
        "export_pr": [
            "Open Workflows and select PR summary or export report zip.",
            "Review the output path before confirming the write.",
            "Attach pr_summary.md to a pull request, or archive the report zip with the run.",
            "Keep the JSON artifact for later automation.",
        ],
    },
    "zh": {
        "guard": [
            "打开“Prompt 守护”页。",
            "粘贴准备交给 Agent 执行的 prompt。",
            "选择“编程”场景和团队 guard policy。",
            "点击“运行守护”，查看决策、风险类别和改写后的 prompt。",
        ],
        "workflows": [
            "打开“工作流”页。",
            "第一次使用时保持“确认后执行”模式。",
            "点击“创建演示数据”，先检查将写入的文件，再确认执行。",
            "用生成的 run 去查看“运行报告”“审计”和“历史”。",
        ],
        "import_external": [
            "打开“工作流”，展开“导入外部 run”。",
            "选择自动识别、Promptfoo、Langfuse、LangSmith、DeepEval 或 prompt-optimizer。",
            "选择导出文件和输出目录，第一次先用“确认后执行”。",
            "打开生成的 run、证据卡、scaffold check 或 prompt asset gap plan。",
        ],
        "report": [
            "在侧边栏选择一个 run。",
            "打开“运行报告”页。",
            "查看部署建议、gate 状态、分数差、置信区间和模型来源。",
            "根据修复样本和失败样本决定下一步检查哪里。",
        ],
        "drift": [
            "选择 run 后打开“模型漂移”页。",
            "检查 baseline 和 candidate 的 provider/model 是否一致。",
            "如果没有 drift artifact，按页面提示运行 model-drift。",
            "如果模型不一致，把它当成 prompt-only 比较有效性的风险。",
        ],
        "audit": [
            "Agent 改完代码后运行 audit-diff。",
            "打开“Agent 改动审计”，查看改动文件、行数和危险路径。",
            "继续检查依赖、workflow、疑似密钥、删除测试和意外文件。",
            "高风险改动合并前需要人工复核。",
        ],
        "history": [
            "对 runs 目录运行 history index。",
            "打开“历史”，按需要复核、高风险、provider 或 model 过滤。",
            "把分数、gate、风险和模型趋势放在一起看。",
            "从表格中找到需要进一步检查的 run。",
        ],
        "project_defaults": [
            "在仓库根目录创建或编辑 .promptcontrol.yaml。",
            "写入 guard_policy、gate_policy、runs_dir、expected_paths 和 test_commands。",
            "刷新 UI，让侧边栏默认值跟随项目配置。",
            "需要临时覆盖时，再用 CLI 或 UI 显式传入新值。",
        ],
        "export_pr": [
            "打开“工作流”，选择生成 PR summary 或导出 report zip。",
            "确认写入路径，再执行导出。",
            "把 pr_summary.md 放进 PR，或把 report zip 和 run 一起归档。",
            "保留 JSON artifact，方便后续自动化。",
        ],
    },
}

ONBOARDING_PATHS = {
    "en": [
        {
            "goal": "I am new and want to see the product first.",
            "start": "Workflows -> Create demo artifacts",
            "next": "Open Run Report, Model Drift, Audit, and History with real local artifacts.",
        },
        {
            "goal": "I need the paper-derived prompt optimization diagnostics.",
            "start": "Research Overview -> `pcl research-quickstart`",
            "next": "Check evidence card, claim-check, gap-status, soft-hard, trajectory, Riccati, and tv-soft readiness.",
        },
        {
            "goal": "I already have eval outputs from Promptfoo, Langfuse, or LangSmith.",
            "start": "Workflows -> Import external run, or CLI `pcl start --choice import`",
            "next": "Then build an evidence card, run scaffold-check, or upgrade to evidence-audit.",
        },
        {
            "goal": "I want to stop vague or risky coding-agent prompts before they run.",
            "start": "Guard Prompt -> choose coding profile and team policy",
            "next": "Save `guard_result.json`, copy the improved prompt, or install IDE/CLI adapters.",
        },
        {
            "goal": "I need to review what an agent changed in a repository.",
            "start": "Agent Diff Audit -> `pcl audit-diff`",
            "next": "Generate a PR summary, build `agent_run.json`, and track the run in History.",
        },
    ],
    "zh": [
        {
            "goal": "我是新用户，想先看产品长什么样。",
            "start": "工作流 -> 创建演示数据",
            "next": "用真实本地 artifacts 打开运行报告、模型漂移、审计和历史。",
        },
        {
            "goal": "我需要论文里的 prompt optimization 诊断能力。",
            "start": "研究总览 -> `pcl research-quickstart`",
            "next": "检查 evidence card、claim-check、gap-status、soft-hard、trajectory、Riccati 和 tv-soft 是否就绪。",
        },
        {
            "goal": "我已经有 Promptfoo、Langfuse 或 LangSmith 的评测导出。",
            "start": "工作流 -> 导入外部 run，或 CLI `pcl start --choice import`",
            "next": "然后生成 evidence card、运行 scaffold-check，或升级到 evidence-audit。",
        },
        {
            "goal": "我想在 coding agent 执行前拦住模糊或高风险 prompt。",
            "start": "Prompt 守护 -> 选择编程场景和团队策略",
            "next": "保存 `guard_result.json`，复制改写后的 prompt，或安装 IDE/CLI adapter。",
        },
        {
            "goal": "我需要复查 agent 到底改了哪些代码。",
            "start": "Agent 改动审计 -> `pcl audit-diff`",
            "next": "生成 PR summary，构建 `agent_run.json`，并在历史页持续追踪。",
        },
    ],
}

TUTORIAL_SECTIONS = {
    "en": [
        {
            "id": "guard",
            "image": "guard",
            "title": "1. Guard a prompt before an agent runs",
            "operation": "Open Guard Prompt, paste the instruction, choose a profile and policy, then run guard.",
            "result": "`guard_result.json`, an improved prompt, risk level, policy violations, and token estimate.",
            "meaning": "You can see whether the prompt is vague, risky, too broad, or missing files/tests.",
            "next_step": "Send the improved prompt to Claude Code, Cursor, Codex, or keep editing it.",
            "command": "pcl guard --prompt \"Fix this bug\" --profile coding --policy examples/guard.policy.yaml --json",
        },
        {
            "id": "workflows",
            "image": "overview",
            "title": "2. Create demo artifacts from the UI",
            "operation": "Open Workflows and click Create demo artifacts.",
            "result": "A local demo project, `runs/demo`, reports, gate result, and `history_index.json`.",
            "meaning": "The dashboard has real artifacts to render, so every tab becomes easier to inspect.",
            "next_step": "Switch to Run Report or History and inspect the generated data.",
            "command": "pcl init --path demo && cd demo && pcl analyze --config promptcontrol.example.yaml --out runs/quick",
        },
        {
            "id": "import_external",
            "image": "overview",
            "title": "3. Import external eval or prompt assets",
            "operation": "Open Workflows, expand Import external run, choose the source tool, and select the export file.",
            "result": "`manifest.json`, `predictions.jsonl`/`metrics.json`, or prompt-optimizer asset and gap-plan artifacts.",
            "meaning": "Promptfoo, Langfuse, LangSmith, DeepEval, and prompt-optimizer outputs can enter the PCL evidence workflow without rebuilding their platforms.",
            "next_step": "Run scaffold-check, build an evidence card, or run evidence-audit when you have baseline/candidate exports.",
            "command": "pcl start --choice import --tool auto --input results.json --out runs/from-external",
        },
        {
            "id": "report",
            "image": "report",
            "title": "4. Analyze, gate, and read the report",
            "operation": "Run analyze from Workflows or CLI, then run gate with a policy.",
            "result": "`metrics.json`, `stats.json`, `explanation.json`, `gate_result.json`, and report files.",
            "meaning": "You can judge whether the candidate prompt improved reliably and passed policy.",
            "next_step": "Keep the prompt, revise it, or inspect failed slices and examples.",
            "command": "pcl analyze --config promptcontrol.example.yaml --out runs/quick && pcl gate --run runs/quick --policy examples/gate.policy.yaml",
        },
        {
            "id": "drift",
            "image": "report",
            "title": "5. Check model provenance and drift",
            "operation": "Open Model Drift or run model-drift between two run directories.",
            "result": "`model_drift.json` with provider/model comparison and drift risk.",
            "meaning": "If models changed, the comparison is not a clean prompt-only comparison.",
            "next_step": "Pin model ids or rerun baseline/candidate under the same model.",
            "command": "pcl model-drift --run runs/current --history runs/previous --out runs/current/model_drift.json",
        },
        {
            "id": "audit",
            "image": "audit_history",
            "title": "6. Audit what the coding agent changed",
            "operation": "Run audit-diff against two git refs after an agent finishes.",
            "result": "`audit_result.json` and `audit_summary.md` with files, line counts, risks, and tests.",
            "meaning": "You can see whether the agent touched dangerous paths, dependencies, workflows, or tests.",
            "next_step": "Review high-risk files before merging, then build an agent-run manifest.",
            "command": "pcl audit-diff --before HEAD~1 --after HEAD --out runs/audit",
        },
        {
            "id": "history",
            "image": "audit_history",
            "title": "7. Build local run history",
            "operation": "Index a runs directory after several analyses or audits.",
            "result": "`history_index.json` with model, score, gate, prompt, and risk timeline data.",
            "meaning": "You can spot score regressions, model changes, and risky agent runs over time.",
            "next_step": "Use History filters to show only high-risk or review-required runs.",
            "command": "pcl history index --runs runs/ --out runs/history_index.json",
        },
        {
            "id": "project_defaults",
            "image": "overview",
            "title": "8. Use project defaults",
            "operation": "Keep `.promptcontrol.yaml` in the repo root for policies, runs, paths, and tests.",
            "result": "Shorter commands because guard, gate, audit-diff, and UI can read local defaults.",
            "meaning": "Teams can share the same policy and expected paths without copy-pasting flags.",
            "next_step": "Edit `.promptcontrol.yaml` when the project policy changes.",
            "command": "pcl guard --prompt \"Fix this bug\" --profile coding",
        },
        {
            "id": "export_pr",
            "image": "audit_history",
            "title": "9. Export and summarize for review",
            "operation": "Generate a PR summary or export a report zip from Workflows.",
            "result": "`pr_summary.md/json` or a zip containing recognized run artifacts.",
            "meaning": "Reviewers get a compact, shareable summary without reading every JSON file.",
            "next_step": "Attach the summary to a PR or archive the zip with the run.",
            "command": "pcl export-report --run runs/quick --out runs/quick/report.zip",
        },
    ],
    "zh": [
        {
            "id": "guard",
            "image": "guard",
            "title": "1. 在 Agent 执行前守护 Prompt",
            "operation": "打开“Prompt 守护”，粘贴指令，选择场景和策略，然后运行守护。",
            "result": "`guard_result.json`、改写后的 prompt、风险等级、策略违规和 token 估算。",
            "meaning": "你可以判断 prompt 是否模糊、危险、范围太宽，或缺少目标文件和测试计划。",
            "next_step": "把改写后的 prompt 发给 Claude Code、Cursor、Codex，或继续手动调整。",
            "command": "pcl guard --prompt \"修复这个 bug\" --profile coding --policy examples/guard.policy.yaml --json",
        },
        {
            "id": "workflows",
            "image": "overview",
            "title": "2. 一键创建演示数据",
            "operation": "打开“工作流”，点击“创建演示数据”。",
            "result": "本地 demo 项目、`runs/demo`、报告、gate 结果和 `history_index.json`。",
            "meaning": "仪表盘会有真实 artifacts 可读，所有页面都能立刻看到示例。",
            "next_step": "切到“运行报告”或“历史”，查看刚生成的数据。",
            "command": "pcl init --path demo && cd demo && pcl analyze --config promptcontrol.example.yaml --out runs/quick",
        },
        {
            "id": "report",
            "image": "report",
            "title": "3. 运行评测、门禁并阅读报告",
            "operation": "在“工作流”里运行 analyze，或用 CLI 运行 analyze，再用策略运行 gate。",
            "result": "`metrics.json`、`stats.json`、`explanation.json`、`gate_result.json` 和报告文件。",
            "meaning": "你可以判断 candidate prompt 是否真的更好，以及是否通过团队策略。",
            "next_step": "保留 prompt、继续修改，或检查退化的 slice 和失败样本。",
            "command": "pcl analyze --config promptcontrol.example.yaml --out runs/quick && pcl gate --run runs/quick --policy examples/gate.policy.yaml",
        },
        {
            "id": "drift",
            "image": "report",
            "title": "4. 检查模型来源和漂移",
            "operation": "打开“模型漂移”，或对两个 run 目录运行 model-drift。",
            "result": "`model_drift.json`，记录 provider/model 对比和漂移风险。",
            "meaning": "如果模型变了，这次比较就不是干净的 prompt-only 比较。",
            "next_step": "固定模型 id，或在同一模型下重新跑 baseline/candidate。",
            "command": "pcl model-drift --run runs/current --history runs/previous --out runs/current/model_drift.json",
        },
        {
            "id": "audit",
            "image": "audit_history",
            "title": "5. 审计编程 Agent 改了什么",
            "operation": "Agent 运行后，对两个 git ref 执行 audit-diff。",
            "result": "`audit_result.json` 和 `audit_summary.md`，包含文件、行数、风险和测试记录。",
            "meaning": "你能看到 Agent 是否改了危险路径、依赖、workflow 或测试文件。",
            "next_step": "合并前优先复查高风险文件，再生成 agent-run manifest。",
            "command": "pcl audit-diff --before HEAD~1 --after HEAD --out runs/audit",
        },
        {
            "id": "history",
            "image": "audit_history",
            "title": "6. 建立本地运行历史",
            "operation": "当你有多次分析或审计后，对 runs 目录建立索引。",
            "result": "`history_index.json`，记录模型、分数、gate、prompt 和风险时间线。",
            "meaning": "你可以发现分数退化、模型变化和高风险 Agent 运行。",
            "next_step": "用“历史”页面过滤只看高风险或需要复核的 run。",
            "command": "pcl history index --runs runs/ --out runs/history_index.json",
        },
        {
            "id": "project_defaults",
            "image": "overview",
            "title": "7. 使用项目默认配置",
            "operation": "在仓库根目录保留 `.promptcontrol.yaml`，记录策略、runs、路径和测试默认值。",
            "result": "guard、gate、audit-diff 和 UI 可以自动读取默认值，命令更短。",
            "meaning": "团队不用反复复制参数，也能共享同一套策略和预期路径。",
            "next_step": "当项目策略变化时，更新 `.promptcontrol.yaml`。",
            "command": "pcl guard --prompt \"修复这个 bug\" --profile coding",
        },
        {
            "id": "export_pr",
            "image": "audit_history",
            "title": "8. 导出报告并生成 PR 摘要",
            "operation": "在“工作流”里生成 PR summary，或导出 report zip。",
            "result": "`pr_summary.md/json`，或一个包含 run artifacts 的 zip。",
            "meaning": "Reviewer 不用逐个打开 JSON，也能快速看到结论和风险。",
            "next_step": "把 summary 放进 PR，或把 zip 和本次 run 一起归档。",
            "command": "pcl export-report --run runs/quick --out runs/quick/report.zip",
        },
    ],
}


TUTORIAL_SECTIONS["zh"] = [
    {
        "id": "guard",
        "image": "guard",
        "title": "1. 在 Agent 执行前守护 Prompt",
        "operation": "打开“Prompt 守护”，粘贴指令，选择场景和策略，然后运行守护。",
        "result": "`guard_result.json`、改写后的 prompt、风险等级、策略违规和 token 估算。",
        "meaning": "你可以判断 prompt 是否模糊、危险、范围太宽，或缺少目标文件和测试计划。",
        "next_step": "把改写后的 prompt 发给 Claude Code、Cursor、Codex，或继续手动调整。",
        "command": "pcl guard --prompt \"修复这个 bug\" --profile coding --policy examples/guard.policy.yaml --json",
    },
    {
        "id": "workflows",
        "image": "overview",
        "title": "2. 一键创建演示数据",
        "operation": "打开“工作流”，点击“创建演示数据”。",
        "result": "本地 demo 项目、`runs/demo`、报告、gate 结果和 `history_index.json`。",
        "meaning": "仪表盘会有真实 artifact 可读，每个 tab 都更容易理解。",
        "next_step": "切到“运行报告”或“历史”，检查刚生成的数据。",
        "command": "pcl init --path demo && cd demo && pcl analyze --config promptcontrol.example.yaml --out runs/quick",
    },
    {
        "id": "import_external",
        "image": "overview",
        "title": "3. 导入外部评测或 prompt 资产",
        "operation": "打开“工作流”，展开“导入外部 run”，选择来源工具和导出文件。",
        "result": "`manifest.json`、`predictions.jsonl` / `metrics.json`，或 prompt-optimizer 资产和 gap plan。",
        "meaning": "Promptfoo、Langfuse、LangSmith、DeepEval 和 prompt-optimizer 的结果可以进入 PCL 证据流程，不需要重造它们的平台。",
        "next_step": "运行 scaffold-check，生成 evidence card；如果有 baseline/candidate 导出，再运行 evidence-audit。",
        "command": "pcl start --choice import --tool auto --input results.json --out runs/from-external",
    },
    {
        "id": "report",
        "image": "report",
        "title": "4. 评测、门禁和报告",
        "operation": "在工作流或 CLI 里运行 analyze，然后用策略运行 gate。",
        "result": "`metrics.json`、`stats.json`、`explanation.json`、`gate_result.json` 和报告文件。",
        "meaning": "你可以判断候选 prompt 是否可靠提升，并且是否通过团队门禁。",
        "next_step": "保留 prompt、继续改写，或检查失败切片和样本。",
        "command": "pcl analyze --config promptcontrol.example.yaml --out runs/quick && pcl gate --run runs/quick --policy examples/gate.policy.yaml",
    },
    {
        "id": "drift",
        "image": "report",
        "title": "5. 检查模型来源和漂移",
        "operation": "打开“模型漂移”，或在两个 run 目录之间运行 model-drift。",
        "result": "`model_drift.json`，包含 provider/model 对比和漂移风险。",
        "meaning": "如果模型变了，这次比较就不是干净的 prompt-only 比较。",
        "next_step": "固定模型 id，或在同一模型下重新跑 baseline/candidate。",
        "command": "pcl model-drift --run runs/current --history runs/previous --out runs/current/model_drift.json",
    },
    {
        "id": "audit",
        "image": "audit_history",
        "title": "6. 审计编程 Agent 改了什么",
        "operation": "Agent 完成后，对两个 git ref 运行 audit-diff。",
        "result": "`audit_result.json` 和 `audit_summary.md`，包含文件、行数、风险和测试记录。",
        "meaning": "你可以看到 agent 是否改了危险路径、依赖、workflow 或测试。",
        "next_step": "合并前复核高风险文件，然后生成 agent-run manifest。",
        "command": "pcl audit-diff --before HEAD~1 --after HEAD --out runs/audit",
    },
    {
        "id": "history",
        "image": "audit_history",
        "title": "7. 建立本地运行历史",
        "operation": "多次 analyze 或 audit 后，对 runs 目录建立索引。",
        "result": "`history_index.json`，包含模型、分数、gate、prompt 和风险时间线。",
        "meaning": "你可以发现分数回退、模型变化和高风险 agent run。",
        "next_step": "用“历史”过滤器只看高风险或需要复核的 run。",
        "command": "pcl history index --runs runs/ --out runs/history_index.json",
    },
    {
        "id": "project_defaults",
        "image": "overview",
        "title": "8. 使用项目默认配置",
        "operation": "在仓库根目录保留 `.promptcontrol.yaml`，记录策略、runs、路径和测试命令。",
        "result": "guard、gate、audit-diff 和 UI 可以读取本地默认值，命令更短。",
        "meaning": "团队可以共享同一套策略和预期路径，不用反复复制参数。",
        "next_step": "项目策略变化时，更新 `.promptcontrol.yaml`。",
        "command": "pcl guard --prompt \"修复这个 bug\" --profile coding",
    },
    {
        "id": "export_pr",
        "image": "audit_history",
        "title": "9. 导出并生成审查摘要",
        "operation": "从工作流生成 PR summary，或导出报告 zip。",
        "result": "`pr_summary.md/json`，或一个包含 run artifacts 的 zip。",
        "meaning": "Reviewer 不用逐个打开 JSON，也能快速看到结论和风险。",
        "next_step": "把 summary 放进 PR，或把 zip 和本次 run 一起归档。",
        "command": "pcl export-report --run runs/quick --out runs/quick/report.zip",
    },
]
